### ISSUE TITLE
Missing Repository 

### ISSUE THREAD

**Issue by jrenai07** [learn-co-curriculum/intro-to-tdd-rspec-and-learn#33]
Hello, I believe I am missing a repository. Every time I open the terminal via the lesson TDD, Rspec, and Learn. I don't see a repository named tdd-rspec-and-learn-q-000. When I type in "open current_age_for_birth_year.rb", into the termianl,  I get a message that says: Couldn't get a file descriptor referring to the console. Also I keep getting a red pop up box that says: Uncaught TypeError: Cannot read property 'path' of undefined. Can someone help pretty please!

**Comment by AnnJohn** [comment]
hi @jrenai07 sorry about the trouble that you're having. We use this space for issues related to the curriculum content so since this is a technical problem, can you file a bug report? If you hover over your profile pic in Learn, you'll see an option from a dropdown menu to "Report a Bug.

Also you can email support@learn.co for help as well. Thanks!
