### ISSUE TITLE
Followed the instructions on the Learn-TDD, Rspec, and Learn and passed when I shouldn't have

### ISSUE THREAD

**Issue by yity42** [learn-co-curriculum/intro-to-tdd-rspec-and-learn#46]
This specific learn has 3 parts that need to be corrected according to the read.me. Which also instructs you to run learn following each correction to identify and correct the next issue. After identifying and correcting the first issue (I think) I ran learn to find the next error and it passed the module. According to the read.me I still have two steps to fix before it should pass. I have attached a screen shot 
![screenshot 3](https://cloud.githubusercontent.com/assets/26237731/23780521/770a22cc-0515-11e7-8ebc-346a1e37bbe0.png)

**Comment by yity42** [comment]
Ok I think I figured it out I was editing the current_age_for_birth_year_spec.rb, not the current_age_for_birth_year file. Still don't know why it let me pass.

**Comment by Joll59** [comment]
@yity42 Sorry for the delayed response. 
Glad you found a solution. You have green lights here because you did not have tests to pass. Hence the 0 examples, 0 failures. 
That can be explained by looking at your code. Line 2 - 10, you created a method within testing environment. This is longer follows spec testing domain specific language.
