### ISSUE TITLE
Unable to fork on the learn IDE

### ISSUE THREAD

**Issue by khalidative** [learn-co-curriculum/intro-to-tdd-rspec-and-learn#58]

**Comment by khalidative** [comment]
problem seems to be solved

**Comment by maxwellbenton** [comment]
Thank you for spotting this and providing feedback, @khalidative.

This issue occurred for multiple students over the past day or so and we believe it was caused by an outage on GitHub (https://www.onmsft.com/news/github-suffers-hours-long-outage-coming-back-online-now). As of now, this lesson is correctly forking and submitting, so I am going to close this issue for now.

If you are still unable to fork this lesson, please re-open this issue. 💙
