### ISSUE TITLE
cannot access links to connect to github

### ISSUE THREAD

**Issue by Jeyavardhini** [learn-co-curriculum/intro-to-tdd-rspec-and-learn#60]

**Comment by Jeyavardhini** [comment]
i am not able to login github but can login through my Learn site,pls help

**Comment by maxwellbenton** [comment]
Hi @Jeyavardhini,

I hope you were able to get assistance with this problem. If you are continuing to experience this sort of issue, it may be best to reach out to the Ask a Question team on Learn. This is a lesson repository and the issues opened here are not immediately checked.

Since this issue is not specifically related to this lesson, I am going to close it. I hope you are able to get assistance with accessing your accounts.
